name: Run query and update table

on: 
  schedule: 
    - cron: "*/5 * * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: create readme.md
        run: |
         chmod +x ${GITHUB_WORKSPACE}/run.sh
         ${GITHUB_WORKSPACE}/run.sh
        shell: bash
