name: Run query and update table

on: 
  schedule: 
    - cron: "*/5 * * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: create readme
        run: |
         chmod +x ./run.sh
         ./run.sh
        shell: bash
