name: Run query and update table

on: 
  schedule: 
    - cron: "*/5 * * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: create readme.md
        run: bash ${GITHUB_WORKSPACE}/run.sh
      
