name: Run query and update table

on: 
  schedule: 
    - cron: "*/5 * * * *"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create readme
        run: ./run.sh
